### ISSUE TITLE
Louder Click Sound?

### ISSUE THREAD

**Issue by Zaidcrowe** [passing/jamulus-metronome#1]
Hello!

Firstly - this is a really cool project :)

I experimented with running this with my drummer, and we quickly established he'd need a louder metronome sound.

How is the 'click' file generated?  I'd like to experiment with different sounds and volumes if possible.

**Comment by passing** [comment]
Hi,

There is unfortunately no easy way to generate that file at the moment. But it can be done as described in the README.md:
https://github.com/passing/jamulus-metronome#capturing-audio

**Comment by Zaidcrowe** [comment]
Many thanks @passing ! I'd glossed over this section of the docs assuming it was something akin to jamuluses server recording feature. 

I now have a drummer proof click 😊

**Comment by passing** [comment]
I'm happy to hear that it worked!
